CREATE
	TABLE
		IF NOT EXISTS MENU (ID SERIAL PRIMARY KEY,
		NAME VARCHAR(255),
		COMPONENT_NAME VARCHAR(255),
		GROUPS_ID BIGINT,
		PATH VARCHAR(255),
		MENUS_ID BIGINT,
		PARENT_MENU VARCHAR(255),
        FOREIGN KEY (GROUPS_ID) REFERENCES GROUPS (ID),
        FOREIGN KEY (MENUS_ID) REFERENCES MENU (ID));

INSERT INTO MENU(NAME, COMPONENT_NAME, GROUPS_ID) VALUES ('MASTER TABLES', 'CORE API', 1),('INVENTORY', 'INV API', 1),
('API HISTORY LOG', 'LOGS', 1),('SECURITY MANAGEMENT', 'COMP NAME', 1), ('REPORTS', 'REPORTS COMP', 1);

INSERT INTO MENU(NAME, COMPONENT_NAME, MENUS_ID, GROUPS_ID, PATH, PARENT_MENU) VALUES ('COMPANY', 'CORE API', 1, 1, '/company', 'MASTER TABLES'),
('DIVISION', 'CORE API', 1, 1, '/division', 'MASTER TABLES'), ('WAREHOUSE', 'CORE API', 1, 1, '/warehouse', 'MASTER TABLES'),
('CHANNEL', 'CORE API', 1, 1, '/channel', 'MASTER TABLES'), ('MANUFACTURING PLANT', 'CORE API', 1, 1, '/mfgplant', 'MASTER TABLES'),
('ITEM', 'EXTERNAL API', 1, 1, '/items', 'MASTER TABLES'), ('CAMPAIGN', 'EXTERNAL API', 1, 1, '/campaign-master', 'MASTER TABLES');

INSERT INTO MENU(NAME, COMPONENT_NAME, MENUS_ID, GROUPS_ID, PATH, PARENT_MENU) VALUES ('WAREHOUSE INVENTORY', 'INV API', 2, 1, '/wmsinventory', 'INVENTORY'),
('MANUFACTURING INVENTORY', 'INV API', 2, 1, '/mfginventory', 'INVENTORY');

INSERT INTO MENU(NAME, COMPONENT_NAME, MENUS_ID, GROUPS_ID, PATH, PARENT_MENU) VALUES ('ITEM API', 'LOGS', 3, 1, 'PATH NAME', 'API HISTORY LOG'),
('WAREHOUSE INV API', 'LOGS', 3, 1, 'PATH NAME', 'API HISTORY LOG'), ('MANUFACTURING INV API', 'LOGS', 3, 1, 'PATH NAME', 'API HISTORY LOG'),
('RETAIL/EXPORT API', 'LOGS', 3, 1, 'PATH NAME', 'API HISTORY LOG'), ('CATALOG API', 'LOGS', 3, 1, 'PATH NAME', 'API HISTORY LOG'),
('WEB API', 'LOGS', 3, 1, 'PATH NAME', 'API HISTORY LOG'), ('CAMPAIGN API', 'LOGS', 3, 1, 'PATH NAME', 'API HISTORY LOG');

INSERT INTO MENU(NAME, COMPONENT_NAME, MENUS_ID, GROUPS_ID, PATH, PARENT_MENU) VALUES ('ITEM API REQUEST', 'LOGS', 15, 1, '/itemApirequest', 'ITEM API'),
('ITEM API RESPONSE', 'LOGS', 15, 1, '/itemApiresponse', 'ITEM API');

INSERT INTO MENU(NAME, COMPONENT_NAME, MENUS_ID, GROUPS_ID, PATH, PARENT_MENU) VALUES ('WAREHOUSE INV API REQUEST', 'LOGS', 16, 1, '/warehouseInvApiRequest', 'WAREHOUSE INV API'),
('WAREHOUSE INV API RESPONSE', 'LOGS', 16, 1, '/warehouseInvApiResponse', 'WAREHOUSE INV API');

INSERT INTO MENU(NAME, COMPONENT_NAME, MENUS_ID, GROUPS_ID, PATH, PARENT_MENU) VALUES ('MANUFACTURING INV API REQUEST', 'LOGS', 17, 1, '/manufacturingInvApi', 'MANUFACTURING INV API'),
('MANUFACTURING INV API RESPONSE', 'LOGS', 17, 1, '/manufacturingInvRespApi', 'MANUFACTURING INV API');

INSERT INTO MENU(NAME, COMPONENT_NAME, MENUS_ID, GROUPS_ID, PATH, PARENT_MENU) VALUES ('RETAIL/EXPORT API REQUEST', 'LOGS', 18, 1, '/retailExportApi', 'RETAIL/EXPORT API'),
('RETAIL/EXPORT API RESPONSE', 'LOGS', 18, 1, '/retailExportRespAPi', 'RETAIL/EXPORT API');

INSERT INTO MENU(NAME, COMPONENT_NAME, MENUS_ID, GROUPS_ID, PATH, PARENT_MENU) VALUES ('CATALOG API REQUEST', 'LOGS', 19, 1, '/requestCatalogApi', 'CATALOG API'),
('CATALOG API RESPONSE', 'LOGS', 19, 1, '/responseCatalogApi', 'CATALOG API');

INSERT INTO MENU(NAME, COMPONENT_NAME, MENUS_ID, GROUPS_ID, PATH, PARENT_MENU) VALUES ('WEB API REQUEST', 'LOGS', 20, 1, '/webApi', 'WEB API'),
('WEB API RESPONSE', 'LOGS', 20, 1, '/webRespApi', 'WEB API');

INSERT INTO MENU(NAME, COMPONENT_NAME, MENUS_ID, GROUPS_ID, PATH, PARENT_MENU) VALUES ('CAMPAIGN API REQUEST', 'LOGS', 21, 1, '/campaignRequestHistory', 'CAMPAIGN API'),
('CAMPAIGN API RESPONSE', 'LOGS', 21, 1, '/campaignResponseHistory', 'CAMPAIGN API');

INSERT INTO MENU(NAME, COMPONENT_NAME, MENUS_ID, GROUPS_ID, PATH, PARENT_MENU) VALUES ('USER', 'COMP_NAME', 4, 1, '/users', 'SECURITY MANAGEMENT'),
('ADMIN', 'COMP_NAME', 4, 1, '/admins', 'SECURITY MANAGEMENT');