server:
  port: 8080
spring:
  application:
    name: MultiTenant
  datasource:
    initialization-mode: always
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'root'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

# following constants are for validation of various Json inputs and Exception handling.
VALIDATION_FAILED: Validation Failed
TMS_EXCEPTION: Tms Exception
ALPHA_NUMERIC_AND_SPACE_REGEX: ^[ a-zA-Z0-9]*$
ALPHA_NUMERIC_REGEX: ^[a-zA-Z0-9]*$

# following messages are for the core classes.
COMPANY_CODE_MAX_LENGTH: 10
DIVISION_CODE_MAX_LENGTH: 10
WAREHOUSE_CODE_MAX_LENGTH: 10

# following are shipper specific.
UPS_BASE_URL: https://wwwcie.ups.com
UPS_CONTENT_TYPE: application/json
UPS_USERNAME: vboopathi
UPS_PASSWORD: vb20UPS@s3
UPS_API_KEY: CD7C3B41BB827C51
UPS_TRANSACTION_SOURCE: S3GTest
UPS_TRANSACTION_ID: s3gTrnx001
UPS_ACCEPT: application/xml
