server:
  #  ssl.key-store: classpath:keystore.p12
  #  ssl.key-store-password: password
  #  ssl.key-store-type: PKCS12
  #  ssl.key-alias: tomcat
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: tms
  datasource:
    url: jdbc:postgresql://mic-tms-pg:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    # Keep the connection alive if idle for a long time (needed in production)
    test-while-idle: true
    validation-query: SELECT 1
    initialization-mode: always
    platform: postgres
    hikari:
      minimum-idle: 20
      maximum-pool-size: 200
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      pool-name: HikariConnectionPool
  jpa:
    # Show or not log for each sql query
    show_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: httptrace
  trace:
    http:
      include: RESPONSE_HEADERS

#eureka:
#  client:
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8000/eureka/

# following constants are for validation of various Json inputs and Exception handling.
VALIDATION_FAILED: Validation Failed
TMS_EXCEPTION: Tms Exception
ALPHA_NUMERIC_AND_SPACE_REGEX: ^[ a-zA-Z0-9]*$
ALPHA_NUMERIC_REGEX: ^[a-zA-Z0-9]*$

# following messages are for the core classes.
COMPANY_CODE_MAX_LENGTH: 10
DIVISION_CODE_MAX_LENGTH: 10
WAREHOUSE_CODE_MAX_LENGTH: 10

# following are shipper specific.
UPS_BASE_URL_SHIPMENTS: https://wwwcie.ups.com/ship/v1801/shipments
UPS_BASE_URL_RATING_SHOP_REQUEST: https://wwwcie.ups.com/ship/v1801/rating/Shop
UPS_CONTENT_TYPE: application/json
UPS_USERNAME: vboopathi
UPS_PASSWORD: vb20UPS@s3
UPS_API_KEY: CD7C3B41BB827C51
UPS_TRANSACTION_SOURCE: Tenant1
#UPS_TRANSACTION_SOURCE: S3GTest
#UPS_TRANSACTION_ID: s3gTrnx001
UPS_ACCEPT: application/json

# common messages are here
SUCCESS_RESPONSE: SUCCESS
FAILURE_RESPONSE: FAILURE