CREATE
	TABLE
		IF NOT EXISTS CARRIER_SERVICE_CODE (CARRIER_CODE VARCHAR(255),
		CARRIER_SHIPMENT_SERVICE VARCHAR(255),
		DESCRIPTION VARCHAR(255),
		PRIMARY KEY (CARRIER_CODE, CARRIER_SHIPMENT_SERVICE),
		CREATED_DATE_TIME TIMESTAMPTZ,
        CREATED_USER VARCHAR(255),
    	LAST_UPDATED_DATE_TIME TIMESTAMPTZ,
      	LAST_UPDATED_USER VARCHAR(255)
);

CREATE
	TABLE
		IF NOT EXISTS CARRIER_PACKAGE_CODE (CARRIER_CODE VARCHAR(255),
		CARRIER_PACKAGE_CODE VARCHAR(255),
		DESCRIPTION VARCHAR(255),
		PRIMARY KEY(CARRIER_CODE, CARRIER_PACKAGE_CODE),
		CREATED_DATE_TIME TIMESTAMPTZ,
        CREATED_USER VARCHAR(255),
        LAST_UPDATED_DATE_TIME TIMESTAMPTZ,
        LAST_UPDATED_USER VARCHAR(255)
		);